'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const teacher=new Image();teacher.src='何老師-去背.png';
const MISS_CD_MS=1200, DASH_MULTIPLIER=2.5;
let cooldownUntil=0,headshots=0;
const CLONE_CHANCE=.05, CLONE_CAST_SECONDS=.9;
const BODY_SCALES=[.75,1,1.3];
let w=1000,h=490,phase='ready',weapon='bat',score=0,combo=0,hits=0,shots=0,missed=0,targets=[],effects=[],startAt=0,last=0,spawnAt=0,attackAt=-1000,muted=false,audioCtx,best=0,introTimer;
try{best=Number(localStorage.getItem('he-teacher-best'))||0}catch{} $('best').textContent=String(best).padStart(5,'0');
teacher.onload=()=>{$('start').disabled=false;$('start').textContent='開始挑戰 ↗'};
teacher.onerror=()=>{$('start').textContent='找不到何老師-去背.png，請放回同一資料夾'};
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
window.addEventListener('resize',resize);resize();
function sound(freq=300,duration=.08,type='square'){if(muted)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq/2,audioCtx.currentTime+duration);g.gain.setValueAtTime(.07,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function speak(){if(muted||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const s=new SpeechSynthesisUtterance('岳父！');s.lang='zh-TW';s.rate=1.1;s.pitch=.8;speechSynthesis.speak(s)}catch{}}
$('sound').onclick=()=>{muted=!muted;$('sound').textContent='音效 '+(muted?'OFF':'ON');if(muted&&'speechSynthesis'in window)speechSynthesis.cancel()};
function select(type){weapon=type;for(const id of ['bat','gun']){$(id).classList.toggle('selected',id===type);$(id).setAttribute('aria-pressed',id===type);$(id).querySelector('em').textContent=id===type?'使用中':'切換'}}
$('bat').onclick=()=>select('bat');$('gun').onclick=()=>select('gun');window.addEventListener('keydown',e=>{if(e.key==='1')select('bat');if(e.key==='2')select('gun')});
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),1100)}
function hud(){ $('score').textContent=String(score).padStart(5,'0');$('status').textContent=combo>1?`${combo} 連擊 / COMBO`:'攔住何老師！'}
function updateCooldown(now){const remaining=phase==='playing'?Math.max(0,cooldownUntil-now):0;$('cooldown').classList.toggle('hidden',remaining===0);$('cooldown').textContent=`攻擊落空！冷卻 ${(remaining/1000).toFixed(1)} 秒`;$('arena').classList.toggle('cooling',remaining>0)}
function beginClone(t){t.casting=CLONE_CAST_SECONDS;t.dashing=false;toast('何老師：影分身之術！');sound(420,.3,'triangle')}
function advanceClone(t,dt){if(!t.casting)return false;t.casting=Math.max(0,t.casting-dt);if(t.casting>0)return true;
 const center=box(t).x/w,spacing=Math.min(.22,Math.max(.12,box(t).width/w*1.2));
 const base=Math.max(.10,Math.min(.90-spacing*2,center-spacing));
 const clones=[0,1,2].map(i=>({...t,x:base+i*spacing,age:0,seed:0,casting:0,dashing:false,dashUntil:0,nextDash:.5+Math.random(),isClone:true}));
 const index=targets.indexOf(t);if(index!==-1)targets.splice(index,1,...clones);
 effects.push({x:center*w,y:box(t).y-box(t).height*.5,life:.65,total:.65,text:'影分身 ×3',kind:'clone'});sound(180,.18,'triangle');return true}
function advanceTarget(t,dt){t.age+=dt;if(t.age>=t.nextDash){t.dashUntil=t.age+.7;t.nextDash=t.dashUntil+2+Math.random()*2;}t.dashing=t.age<t.dashUntil;t.z+=dt*t.speed*(t.dashing?DASH_MULTIPLIER:1)}
function start(){if(phase==='intro'||phase==='playing')return;phase='intro';cooldownUntil=0;updateCooldown(performance.now());clearTimeout(introTimer);$('result').classList.add('hidden');$('intro').classList.remove('hidden');$('start').disabled=true;$('start').textContent='何老師：「岳父！」';$('bubble').textContent='岳父！！';speak();score=combo=hits=shots=missed=headshots=0;targets=[];effects=[];hud();$('time').innerHTML='60<span> SEC</span>';$('time').classList.remove('urgent');introTimer=setTimeout(()=>{$('intro').classList.add('hidden');phase='playing';startAt=performance.now();spawnAt=startAt;attackAt=-1000;last=startAt},1600)}
$('start').onclick=start;$('restart').onclick=start;
function finish(){phase='ended';cooldownUntil=0;updateCooldown(performance.now());$('time').innerHTML='0<span> SEC</span>';$('status').textContent='挑戰結束';$('finalScore').textContent=score;$('stats').textContent=`命中 ${hits} 次 · 爆頭 ${headshots} 次 · 命中率 ${shots?Math.round(hits/shots*100):0}% · 漏掉 ${missed} 位`;$('resultTitle').textContent=score>=5000?'稱呼保衛大師！':score>=2000?'岳父防線，守住了！':'何老師還想再喊一次。';const isRecord=score>best;if(isRecord){best=score;try{localStorage.setItem('he-teacher-best',String(best))}catch{}}$('best').textContent=String(best).padStart(5,'0');$('record').textContent=isRecord?'★ 新的個人最高紀錄！':`個人最高紀錄：${best} 分`;$('result').classList.remove('hidden');sound(600,.35,'triangle')}
function box(t){const size=h*(.15+t.z*.34)*(t.scale??1);return{x:(t.x+Math.sin(t.age*2+t.seed)*.035)*w,y:h*(.29+t.z*.64),width:size*.46,height:size}}
function headBox(t){const b=box(t);return{x:b.x+b.width*.055,y:b.y-b.height*.867,rx:b.width*.21,ry:b.height*.13}}
function isHeadshot(t,x,y){const head=headBox(t);return ((x-head.x)/head.rx)**2+((y-head.y)/head.ry)**2<=1}
function attack(x,y){const now=performance.now();if(phase!=='playing')return;if(now-startAt>=60000){finish();return}if(now<cooldownUntil||now-attackAt<(weapon==='bat'?330:200))return;attackAt=now;shots++;sound(weapon==='bat'?150:700,.10,weapon==='bat'?'triangle':'sawtooth');let target=null,tooFar=false;for(const t of [...targets].sort((a,b)=>b.z-a.z)){const b=box(t),pad=weapon==='bat'?22:4;if(x>b.x-b.width/2-pad&&x<b.x+b.width/2+pad&&y>b.y-b.height-pad&&y<b.y+pad){if(weapon==='bat'&&t.z<.61){tooFar=true;continue}target=t;break}}
if(target?.casting){shots--;toast('結印中！等分身出現再攻擊');return}
effects.push({x,y,life:.25,total:.25,kind:weapon});if(target&&weapon==='gun'&&Math.random()<CLONE_CHANCE){hits++;combo++;if(isHeadshot(target,x,y))headshots++;beginClone(target);hud();return}if(target){targets.splice(targets.indexOf(target),1);combo++;hits++;const headshot=isHeadshot(target,x,y);if(headshot)headshots++;const points=(weapon==='bat'?150:100)*(headshot?2:1)+Math.min(combo-1,10)*10;score+=points;effects.push({x,y:y-30,life:.8,total:.8,text:`${headshot?'爆頭！ ':''}+${points}`,kind:headshot?'headshot':'points'});if(headshot)toast('爆頭！基礎分數 ×2');else if(combo%5===0)toast(`${combo} 連擊！加分持續提升`)}else{combo=0;cooldownUntil=now+MISS_CD_MS;updateCooldown(now);if(tooFar)toast('太遠了！球棒要等他靠近才能命中')}hud()}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();attack(e.clientX-r.left,e.clientY-r.top)});
function background(){ctx.fillStyle='#dce5cf';ctx.fillRect(0,0,w,h);ctx.fillStyle='#c6d3b9';ctx.fillRect(0,h*.35,w,h*.65);ctx.strokeStyle='#b3c2a4';ctx.lineWidth=1;for(let i=-6;i<8;i++){ctx.beginPath();ctx.moveTo(w*.5+i*25,h*.35);ctx.lineTo(w*.5+i*w*.22,h);ctx.stroke()}for(let i=0;i<7;i++){const y=h*(.35+.65*(i/6)**1.7);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.fillStyle='#cdd8c0';for(let i=0;i<6;i++){const x=i*w/5-25;ctx.fillRect(x,h*.12,80,h*.23);ctx.fillStyle='#b4c4a5';for(let j=0;j<3;j++)ctx.fillRect(x+13+j*21,h*.17,10,20);ctx.fillStyle='#cdd8c0'}ctx.fillStyle='#d7fa5524';ctx.fillRect(0,h*.68,w,h*.32);ctx.setLineDash([8,8]);ctx.strokeStyle='#7e9663';ctx.beginPath();ctx.moveTo(0,h*.68);ctx.lineTo(w,h*.68);ctx.stroke();ctx.setLineDash([])}
function drawTarget(t){const b=box(t);if(t.casting){ctx.save();ctx.strokeStyle='#7945b8';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(b.x,b.y-b.height*.45,b.width*.8,b.height*.6,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#65339b';ctx.font='bold 15px Arial';ctx.textAlign='center';ctx.fillText('影分身之術！',b.x,Math.max(55,b.y-b.height-14));ctx.restore()}else if(t.isClone){ctx.fillStyle='#65339b';ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.fillText('分身',b.x,b.y-b.height-12)}if(t.dashing){ctx.strokeStyle='#c45b28';ctx.lineWidth=3;for(let j=0;j<3;j++){ctx.beginPath();ctx.moveTo(b.x-b.width*.7-j*6,b.y-b.height*.3-j*12);ctx.lineTo(b.x-b.width*.7-j*6,b.y-b.height*.3-j*12-24);ctx.stroke()}ctx.fillStyle='#a83f1b';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText('突然加速！',b.x,b.y-b.height-10)}ctx.fillStyle='#43533330';ctx.beginPath();ctx.ellipse(b.x,b.y,b.width*.65,9+t.z*5,0,0,Math.PI*2);ctx.fill();if(teacher.complete&&teacher.naturalWidth)ctx.drawImage(teacher,teacher.naturalWidth*.34,teacher.naturalHeight*.04,teacher.naturalWidth*.29,teacher.naturalHeight*.92,b.x-b.width/2,b.y-b.height,b.width,b.height);if(t.z>.61){ctx.fillStyle='#e5ff91';ctx.fillRect(b.x-23,b.y+8,46,15);ctx.fillStyle='#354322';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.fillText('可揮棒',b.x,b.y+19)}}
function frame(now){const dt=Math.min((now-last)/1000,.1)||0;last=now;updateCooldown(now);background();if(phase==='playing'){const elapsed=(now-startAt)/1000;if(elapsed>=60)finish();else{$('time').innerHTML=`${Math.ceil(60-elapsed)}<span> SEC</span>`;$('time').classList.toggle('urgent',elapsed>=50);if(now>=spawnAt){targets.push({x:.12+Math.random()*.76,z:0,age:0,scale:BODY_SCALES[Math.floor(Math.random()*BODY_SCALES.length)],seed:Math.random()*6,nextDash:1+Math.random()*1.5,dashUntil:0,dashing:false,speed:.11+Math.random()*.04+elapsed*.001});spawnAt=now+Math.max(430,1050-elapsed*9)}for(let i=targets.length-1;i>=0;i--){const t=targets[i];if(advanceClone(t,dt))continue;advanceTarget(t,dt);if(t.z>1){targets.splice(i,1);missed++;combo=0;score=Math.max(0,score-50);effects.push({x:box(t).x,y:h*.8,life:.8,total:.8,text:'漏掉 −50',kind:'miss'});hud()}}}}
targets.sort((a,b)=>a.z-b.z).forEach(drawTarget);for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.life<=0){effects.splice(i,1);continue}ctx.save();ctx.globalAlpha=e.life/e.total;if(e.text){ctx.fillStyle=e.kind==='miss'?'#aa442d':e.kind==='headshot'?'#b34a08':e.kind==='clone'?'#65339b':'#344919';ctx.font='900 26px Arial';ctx.textAlign='center';ctx.fillText(e.text,e.x,e.y-(1-e.life/e.total)*35)}else{ctx.strokeStyle=e.kind==='bat'?'#faffc0':'#fff';ctx.lineWidth=e.kind==='bat'?9:3;ctx.beginPath();if(e.kind==='bat')ctx.arc(e.x,e.y,45+(1-e.life/e.total)*20,-2.5,.8);else{ctx.arc(e.x,e.y,18,0,Math.PI*2);ctx.moveTo(e.x-27,e.y);ctx.lineTo(e.x+27,e.y);ctx.moveTo(e.x,e.y-27);ctx.lineTo(e.x,e.y+27)}ctx.stroke()}ctx.restore()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
